# Generated by Django 5.0.6 on 2024-09-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
